### ISSUE TITLE
Prodops.guide is public

### ISSUE THREAD

**Issue by azizshamim** [github/prodops-guide#3]
I noticed that this url is live: http://prodops.guide/

* Question: The website looks pre-production. Curious if this is meant to be public and published.
* The [README](https://github.com/github/prodops-guide#roadmap) has broken links, referencing a roadmap that doesn't exist in the repository and permission notices.

**Comment by brntbeer** [comment]
@leefaus any update on this? I saw we're sharing this with more and more people and the state of the repo looks like it's a bit away from wanting to share with the public

**Comment by azizshamim** [comment]
@leefaus moved it to his personal namespace. ✔️
